#!/usr/bin/env python3
"""Generate assets/timezones.js — IANA time zone to ISO 3166-1 alpha-2.

The homepage's country lookup offers "use my region". Every obvious way to
implement that is wrong for this site's audience: the Geolocation API throws a
permission prompt and hands back coordinates that then need a reverse-geocoding
request, and IP lookup services are a third-party request that tells someone
else you were reading a censorship tracker. Both leak.

The browser already knows roughly where it is, and will say so for free:
Intl.DateTimeFormat().resolvedOptions().timeZone. Mapping that to a country is
a table lookup, which means the whole feature runs offline, inside the page,
with no prompt and no request. It is a guess — a VPN or a manually set clock
will fool it, which is exactly why the button fills the selector in rather than
navigating, so the visitor can see and correct what it picked.

Built from the system's own /usr/share/zoneinfo/zone.tab, with canonical
territory names resolved through country_registry.json.

    python3 build_timezones.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from country_registry import load_registry

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "assets" / "timezones.js"
ZONE_TAB = Path("/usr/share/zoneinfo/zone.tab")

# Zones renamed over the years. Browsers are inconsistent about which spelling
# they report — older Safari still says Asia/Calcutta — and zone.tab only lists
# the current name, so the retired ones are mapped here by hand.
ALIASES = {
    "Asia/Calcutta": "Asia/Kolkata",
    "Asia/Katmandu": "Asia/Kathmandu",
    "Asia/Rangoon": "Asia/Yangon",
    "Asia/Saigon": "Asia/Ho_Chi_Minh",
    "Asia/Istanbul": "Europe/Istanbul",
    "Europe/Kiev": "Europe/Kyiv",
    "Europe/Nicosia": "Asia/Nicosia",
    "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
    "America/Godthab": "America/Nuuk",
    "Africa/Asmera": "Africa/Asmara",
    "Atlantic/Faeroe": "Atlantic/Faroe",
    "Pacific/Ponape": "Pacific/Pohnpei",
    "Pacific/Truk": "Pacific/Chuuk",
    "US/Eastern": "America/New_York",
    "US/Central": "America/Chicago",
    "US/Mountain": "America/Denver",
    "US/Pacific": "America/Los_Angeles",
    "GB": "Europe/London",
    "GB-Eire": "Europe/London",
    "Eire": "Europe/Dublin",
    "Egypt": "Africa/Cairo",
    "Hongkong": "Asia/Hong_Kong",
    "Iran": "Asia/Tehran",
    "Israel": "Asia/Jerusalem",
    "Japan": "Asia/Tokyo",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Singapore": "Asia/Singapore",
    "Turkey": "Europe/Istanbul",
}


def main() -> int:
    if not ZONE_TAB.is_file():
        print(f"{ZONE_TAB} not found — this needs a system tz database", file=sys.stderr)
        return 1

    try:
        registry = load_registry()
    except ValueError as exc:
        print(f"{exc}", file=sys.stderr)
        return 1

    zones: dict[str, str] = {}
    country_names: dict[str, str] = {}
    map_aliases = registry.map.get("iso_aliases") or {}
    for line in ZONE_TAB.read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        iso = parts[0].strip()
        zone = parts[2].strip()
        zones[zone] = iso
        canonical_iso = map_aliases.get(iso, iso)
        canonical_name = registry.canonical_name(canonical_iso)
        if canonical_name:
            country_names[zone] = canonical_name

    for old, new in ALIASES.items():
        if new in zones:
            zones.setdefault(old, zones[new])
            if new in country_names:
                country_names.setdefault(old, country_names[new])

    body = json.dumps(dict(sorted(zones.items())), indent=0, ensure_ascii=False)
    names_body = json.dumps(dict(sorted(country_names.items())), indent=0, ensure_ascii=False)
    OUT.write_text(
        "// IANA time zone -> ISO 3166-1 alpha-2, generated by build_timezones.py\n"
        "// from the system tz database and country_registry.json. Loaded on\n"
        "// demand, only when a visitor presses \"use my region\" — see\n"
        "// build_timezones.py for why the region guess is made from the clock\n"
        "// rather than from geolocation or an IP lookup, and why it is offered\n"
        "// as a guess the visitor can correct.\n"
        "window.TZ_TO_ISO = " + body + ";\n"
        "// Only zones whose ISO code is in the canonical registry receive a\n"
        "// display name; the ISO table intentionally still covers every zone.\n"
        "window.TZ_TO_COUNTRY = " + names_body + ";\n",
        encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(zones)} zones "
          f"({len(set(zones.values()))} territories), "
          f"{len(country_names)} canonical names, {OUT.stat().st_size // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
