#!/usr/bin/env python3
"""The static prerendered index must stay in sync with the CSV.

index.html carries a baked platform list (between the PRERENDER markers) so
crawlers and no-JS visitors see the data. It is generated by prerender.py, which
means it can go stale the moment someone edits censorship_data.csv and forgets
to re-run it. This test fails when that happens: every platform in the CSV must
appear as a prerendered row, and there must be no extra or missing rows.

Fix a failure by running:  python3 prerender.py
"""
from __future__ import annotations

import csv
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "censorship_data.csv"
INDEX = ROOT / "index.html"


def main() -> int:
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        csv_platforms = {
            (row.get("platform") or "").strip()
            for row in csv.DictReader(f)
            if (row.get("platform") or "").strip()
        }

    index_html = INDEX.read_text(encoding="utf-8")
    rendered = set(re.findall(r'<h3 class="pr-name">(.*?)</h3>', index_html))
    # Names are HTML-escaped in the page; compare on the same footing.
    expected = {html.escape(p) for p in csv_platforms}

    missing = expected - rendered
    extra = rendered - expected
    assert not missing, (
        f"{len(missing)} platform(s) in the CSV but not prerendered "
        f"(run: python3 prerender.py): {sorted(missing)}"
    )
    assert not extra, (
        f"{len(extra)} prerendered platform(s) no longer in the CSV "
        f"(run: python3 prerender.py): {sorted(extra)}"
    )

    print(f"ok: {len(rendered)} platforms prerendered, in sync with the CSV")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
